#http://localhost:1050/autodealer-apigateway/auto-dealer/
server:
  servlet:
    context-path: /${spring.application.name}
  port: 1046
spring:
  application:
    name: auto-dealer
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/cardealer
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
